language: android
android:
  components:
  - tools
  - platform-tools
  - android-23
  - build-tools-23.0.1
  - extra-android-m2repository
  - extra-android-support

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle